### ISSUE TITLE
Episodal Clustering 

### ISSUE THREAD

**Issue by ifilonenko** [cuappdev/podcast-web#15]
Need to cluster episodes so that we could determine how to partition data on the servers. 
Cant simply index on name or id, because search results may tend to give for example:

> search "chinese"
> chinese mytholodgy
> history of china
> the silk road
> ...

As such, we would need to group these results in a single cluster and write them to cassandra so the writes don't hit every server.

Investigate clustering techniques using TFIDF of the descriptions, tags, and categories. 
Use truncated-SVDs with TSNE.

**Comment by jk2227** [comment]
![image](https://cloud.githubusercontent.com/assets/8561804/19624154/5252fa28-98b7-11e6-909c-bfe558c71647.png)

Tentative results using descriptions from all episodes scraped from audiosearch; 23 topics generated by MALLET with hyperparameter specified as 20

**Comment by jk2227** [comment]
![image](https://cloud.githubusercontent.com/assets/8561804/19624298/644a35ec-98bd-11e6-996a-68ec0a63630e.png)

Topic modeling using MALLET based on JUST categories of episodes scraped from audiosearch; 15 topics generated by MALLET
