### ISSUE TITLE
Create Session case class

### ISSUE THREAD

**Issue by amizra** [cuappdev/podcast-web#17]
We want a case class that represents sessions:

    case class SessionEntity {
        token: string;
        updateToken: string;
        expiresAt: string;
        userId: foreign key int;
    }

There is a `/sessions` endpoint. When the update token is sent from the frontend to this endpoint, a new session tuple is generated with a new token, update token, and expires at.

Token: String used to authenticate requests. 
Update token: Token used to get fresh session information from `/sessions` endpoint.
Expires at: The time at which the current token expires.

The token is in with every request. If the token is valid, we query the database for the user associated with the session and eagerly load the user. If the token is expired, we give the client an error.

**Comment by amizra** [comment]
After auth with Facebook, you either create a user or grab the user and return. You either create a Session or regenerate the Session and return it as a response.

Need a case class for this response type that extends beyond the normal response case class.

    {success: true,
    data: {
        user: {<user>},
        session: {<session>}
    },
    }

**Comment by Jma353** [comment]
This is complete
