### ISSUE TITLE
Case classes for allowed update operations

### ISSUE THREAD

**Issue by amizra** [cuappdev/podcast-web#19]
We should have case classes for various allowed subsets of fields that we're allowed to update during a single update request (allowed "atomic" operations).

These case classes should be parsed upon request. Then the case class should be merged with a case class `Update` mapping fields to options. Then we update only those fields in the `Update` that are not none in whatever Entity we are working with.

**Comment by Jma353** [comment]
I don't really see anything we need to update for the Entities we're currently dealing with.  I think we should explicitly create case classes for the fields on entities that ARE updateable whenever we see those in the future.

Closing this for now.
